// This file is automatically generated. Do not edit it directly.
export async function requireSupabaseAuth<T>(next: () => Promise<T>) {
  // Route-level auth checks can be wired to React Router loaders or guards here.
  return next();
}

