// This file is automatically generated. Do not edit it directly.
import { supabase } from "./client";

// React Router-compatible helper used by the app shell when auth headers are needed.
export async function attachSupabaseAuth<T>(next: () => Promise<T>) {
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  void token;
  return next();
}
